name: Deploy

on: [workflow_dispatch, workflow_call]

jobs:
  deploy-github-pages:
    name: Github Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2.1.2

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/WebGL/${{ env.PROJECT_NAME }}

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v1