name: Deploy

on: [workflow_dispatch, workflow_call]

jobs:
  deployToGithubPages:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectName:
          - GravityBall
        targetPlatform:
          - WebGL
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2.1.2

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/${{ matrix.targetPlatform }}/${{ matrix.projectName }}

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v1