name: Deploy

on: 
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string

env:
  targetPlatform: WebGL

jobs:
  deploy-github-pages:
    name: Github Pages
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.projectName }}${{ env.targetPlatform }}GithubPages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2.1.2

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.projectName }}${{ env.targetPlatform }}
          path: build/${{ env.targetPlatform }}

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/${{ env.targetPlatform }}/${{ inputs.projectName }}

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v1