name: Deploy

on: 
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string

jobs:
  deploy-github-pages:
    name: Github Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2.1.2

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.PROJECT_NAME }}WebGL
          path: build/WebGL

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/WebGL/${{ inputs.PROJECT_NAME }}

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v1