name: Unity

on: [workflow_dispatch, pull_request]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  build:
    name: Build
    needs: test
    uses: ./.github/workflows/build.yml
  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml