name: Unity

on: [workflow_dispatch, pull_request]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  build:
    name: Build
    needs: test
    uses: ./.github/workflows/build.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}