name: Unity

on: [workflow_dispatch, pull_request]

env:
  PROJECT_NAME: GravityBall
  PROJECT_PATH: ./

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      PROJECT_PATH: "./"
  build:
    name: Build
    needs: test
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      PROJECT_NAME: "GravityBall"
  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      PROJECT_NAME: "GravityBall"